apiVersion: v1
kind: Service
metadata:
  name: llm-gateway
  labels:
    app: llm-gateway
  {{- if eq .Values.gateway.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: llm-gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: 8000
