{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-gateway
  labels:
    release: {{ .Values.monitoring.serviceMonitor.release }}
spec:
  selector:
    matchLabels:
      app: llm-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-model
  labels:
    release: {{ .Values.monitoring.serviceMonitor.release }}
spec:
  selector:
    matchLabels:
      app: llm-model
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
